### ISSUE TITLE
SQAN: Extracting DICOM metadata into CSV/Excel spreadsheet for review (dynamic field selection?)

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#109]
From John West: 

We would like to be able to extract key dicom fields and sequence name and image counts from a particular study into a CSV/Excel spreadsheet to help track the data acquired for subjects in the study.  Ideally this would be something we could do through the WebUI.  While we have certain dicom fields we would like to capture, it would be great if this would be something that could be dynamic (i.e. for a data pull we select which fields we grab).  Also, it would be nice if a particular pull could be saved to be repulled at any time (kind of like a report in RedCap).

I realize not all of the above is easy to do, so we should think about what is most criticial and go from there.  I think it would be a good idea to have a working session dedicated to this.  Happy to come down to Bloomington to do so.

**Comment by jdwest0711** [comment]
Hello all.  We have a meeting about the project that would utilize this data on 9/23.  Is there any chance we could get a sample extraction of the information by then that I could show everyone and get their feedback on?  I don't expect it to be a full feature by then of course, but making sure we are on the right track would be very helpful.

**Comment by agopu** [comment]
Hi @jdwest0711 sure we can prototype something up ahead of your Sep 23rd meeting!

**Comment by agopu** [comment]
> Forwarded Conversation
> Subject: RE: Prototype IIBIS Reports
> ------------------------
> 
> From: West, John D. <jdwest@iupui.edu>
> Date: Fri, Sep 13, 2019 at 4:17 PM
> To: Young, Michael David <youngmd@iu.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Awesome.  Thanks Mike.  I'll look into this and give you feedback Monday.  Have a great weekend!
> 
> -----Original Message-----
> From: Young, Michael David <youngmd@iu.edu> 
> Sent: Friday, September 13, 2019 4:01 PM
> To: West, John D. <jdwest@iupui.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>; Paramasivam, Meenakshisundaram <mparamas@iupui.edu>; Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> Subject: Prototype IIBIS Reports
> 
> Hi John,
> 
> I've constructed some sample reports based on our discussions.  I decided to take the approach of splitting each research query into two reports.  The first has records that are common across all series in a given exam and has a row per exam (so subjects with multiple exams are repeated).  The second has a row for each subject, and 3 columns for each series:  scan_count, img_count, and p_CoilString.  If scan_count is greater than 1 then img_count is the max img_count across the repeated scans.  p_CoilString shows a ' | ' concatenated  list of the p_CoilString values for each exam. 
> 
> Look forward to getting your feedback on this.  Once we've settled on a layout/format I can move forward on creating a UI to enable on-demand customized generation of these reports.
> 
> -Mike
> 
> 
> 
> ----------
> From: West, John D. <jdwest@iupui.edu>
> Date: Mon, Sep 16, 2019 at 1:21 PM
> To: Young, Michael David <youngmd@iu.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Hi Mike.
> 
> Ok, I think I do like the series layout, but it makes it hard to determine which is which on the sheet.  For example in 2016-00203 scan 19317 and 19319 have two scans on different dates, but on the series sheet you can't tell which is which and having the max image count between the two of them for a certain series is misleading as you have no idea if time 1 was good and time 2 was bad or vice versa as in that case only one of them has to be good.  I think even on the series sheet, we would need a row for each instance of the subject and add a column for date and time.
> 
> Let me know if you need to chat via zoom to discuss.
> 
> Thanks!
> -John
> 
> ----------
> From: Young, Michael David <youngmd@iu.edu>
> Date: Mon, Sep 16, 2019 at 2:41 PM
> To: West, John D. <jdwest@iupui.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Ok, I've modified it to have a row per exam on the series sheet with the timestamp included. 
> 
> 
> 
> ----------
> From: West, John D. <jdwest@iupui.edu>
> Date: Mon, Sep 16, 2019 at 2:55 PM
> To: Young, Michael David <youngmd@iu.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Hi Mike. 
> 
> This looks good.  Do you want to start prototyping the UI, or would you want to wait until we get final feedback from our group on Monday?
> 
> -----Original Message-----
> From: Young, Michael David <youngmd@iu.edu> 
> Sent: Monday, September 16, 2019 2:42 PM
> To: West, John D. <jdwest@iupui.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>; Paramasivam, Meenakshisundaram <mparamas@iupui.edu>; Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> ----------
> From: West, John D. <jdwest@iupui.edu>
> Date: Wed, Sep 18, 2019 at 3:03 PM
> To: Young, Michael David <youngmd@iu.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Hi Mike.
> 
> Thanks for working on this.  We have been discussing internally a bit and found some issues with our RedCap database that will make it difficult to incorporate the data you are providing.  Emphasis on our issues.  We think we may have found a solution but I would hold off on working on this until we can figure it out and determine if this makes sense for our current need or not.
> 
> That being said, having this ability to extract information from the SQAN system will be beneficial in other areas so I think it is a good thing to pursue.  It may just not have the same urgency now if the RedCap issue doesn't get resolved and we have to go in another direction for our tracking needs.
> 
> Thanks.
> -John
> 
> ----------
> From: Young, Michael David <youngmd@iu.edu>
> Date: Wed, Sep 18, 2019 at 3:04 PM
> To: West, John D. <jdwest@iupui.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Well, for what it's worth you can check this out anyways:
> https://rady-test.sca.iu.edu/report
> If you're not logged in you may need to click on that link again after logging in.
> -Mike
> 
> ----------
> From: West, John D. <jdwest@iupui.edu>
> Date: Wed, Sep 18, 2019 at 3:22 PM
> To: Young, Michael David <youngmd@iu.edu>
> Cc: Gopu, Arvind <agopu@iu.edu>, Paramasivam, Meenakshisundaram <mparamas@iupui.edu>, Avena Koenigsberger, Andrea Itzel <aiavenak@indiana.edu>
> 
> 
> Hey Mike.  This is really really cool.  Sorry that we found an issue after you worked on it.  My bad.  Essentially what we are dealing with is trying to be able to successfully import the data into RedCap.  Our redcap IDs have _# after the subject ID to indicate the timepoint.  We don’t have that information here, so we would have to match by date and we are figuring out the best way to do that. In addition as you know we would need to ingest all the legacy data for the studies.  This would mean uploading all DICOMs which would take some time.  Rachael has been working in parallel on another method to extract the data on our server which turned out to be simpler than we first thought, and since it has the _#, would be easier to match with RedCap. That being said, what you have put together is really very cool, and I think will benefit our researchers immensely going forward, especially if at some point we can expand it to ask for other fields to extract.  So this is definitely not wasted effort just not as urgent as I originally though.  Very sorry about that. Thanks.-John
> 
>

**Comment by agopu** [comment]
We have a prototype but it's unclear if it will be used. I will close this ticket - feel free to reopen it or open a new one if the issue comes up again.
