### ISSUE TITLE
SQAN: Merge Harvard/Dartmouth branches back to master

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#124]
Among other features, we made 3 significant changes/updates:
- Moved skip keywords from code to UI/DB (currently, only allows skip, custom, default, at a modality level).
- Ingestion UI which calls incoming module.
- Basic authN/Z + sign on added (previously, it was IU CAS only).

**Comment by agopu** [comment]
I believe this got done and was documented elsewhere?

**Comment by youngmd** [comment]
No, these changes have not been merged into master.

**Comment by agopu** [comment]
Ah, right, sorry I misread the ticket earlier ... and was thinking about merging the changes between Dartmouth<->Harvard.

**Comment by youngmd** [comment]
I've created a new branch called old_master for ongoing angularJS related work.  The dartmouth/harvard branches have been merged into this branch and the code is live on rady-test.sca.  Some minor cleanup remains to be done, but after that we can look into whether we want to proceed with deploying this to production.

**Comment by youngmd** [comment]
This ticket is no longer relevant in light of the completed Vue transition.  All applicable features of these branches have been integrated into the redesign.
