### ISSUE TITLE
SQAN: Develop Precision QC setup (fka Whitelist)

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#125]
Mostly because of stakeholder (RADY) needs, our QC system has always been based on a) a template data set b) a blacklist model in which one could exclude series, keywords, etc.

Based on our own wishlist item and per a requirement expressed by our Dartmouth/Harvard collaborators, we would like to develop a whitelist based model in which only certain keywords and/or series are QCed. This is relatively straight forward at least when set at the level of modality.

**Comment by agopu** [comment]
This would need changes both on the UI side and on the DB/QC backend.

**Comment by agopu** [comment]
@youngmd has implemented an early version of this and has deployed on rady-test.sca.iu.edu ; we plan to push this production this week. Mike is going the extra mile in saving all manual QC overrides and comments while reQCing all failures with the new model.

**Comment by youngmd** [comment]
This has been deployed to production.  We have a meeting on Dec 9th for potential updates/changes to the QC key list, but any issues arriving from that should receive their own tickets.
