### ISSUE TITLE
SQAN: Display precise QC criteria on demand (within Exam and QC detail views)

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#126]
As we move in the direction of allowing customizations to QC criteria, we have to also add this info - precise QC criteria - to various portal views including the Exams and the QC detail views.

**Comment by youngmd** [comment]
This is effectively done now for the current implementation of QC, as we indicate which keywords have been evaluated.  If we do decide to implement fully customizable QC we will expand the level of QC criteria stored and displayed.
