### ISSUE TITLE
SQAN: Composite or relative QC criteria (Harvard criteria)

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#128]
The SQAN QC setup has always allowed non-absolute criteria - for e.g., ranges, percent shifts and exclusions. Our Harvard collaborator Sylvain Bouix is interested in setting up composite/relative QC criteria. This could be:
- If A present, then QC B as follow.
- If A=X1, then expect B=Y1; but If A=X2, then expect B=Y2.
- QC criteria for B is function of A's value; B=f(A).
- ...

**Comment by youngmd** [comment]
This is just a variant of the existing custom handlers, some of which already do look at multiple keywords to evaluate compliance.
