### ISSUE TITLE
SQAN: Add research and PI information to "Missing templates" listing

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#130]
Per discussion in today's zoom call, before pushing current new updates on test to production, we will add research and PI information to the list of research studies that don't have a template.

**Comment by youngmd** [comment]
This is done and live on production.  Also added csv export option to download table.  There are some missing IIBIS entries due to our iibis table not being updated.  Looks like the API access is broken, I'll create another ticket for that.
