### ISSUE TITLE
SQAN: Header search & dump/report feature within the portal

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#133]
We've discussed in recent collab/zoom meetings the wish to have the ability to pick a research study (IIBIS), then search for specific keywords (metadata headers/tags) and dump the header info. Ideally the user would also be able to download the dumped data as a CSV. 

@youngmd has been prototyping this feature - currently available at https://rady-test.sca.iu.edu/report

**Comment by agopu** [comment]
![image](https://user-images.githubusercontent.com/2206370/75785535-e4b3f100-5d31-11ea-95ee-55f79ca4b66d.png)

**Comment by youngmd** [comment]
Implemented the report page in the Vue instance.  I also included an additional tab layer to present different series in different tables to avoid excessive horizontal scrolling.  

TODO:  Export to csv/json

![Screen Shot 2020-04-24 at 3 39 41 PM](https://user-images.githubusercontent.com/1247513/80250558-18c8d580-8642-11ea-8cb0-b986d7249296.png)

**Comment by agopu** [comment]
This fell through the cracks last year
- [ ] Export to csv/json

**Comment by agopu** [comment]
I don't think we implemented the export to CSV feature but overall this feature has been in place since spring 2021.

Closing stale ticket; SQAN has not been as much of a priority and has been in steady state mode. CC @charlesbrandt
