### ISSUE TITLE
SQAN: Evaluate value & Implement re-usable filter functionality

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/SQAN#134]
Many sections of the interface utilize a client-side filter to narrow results. 

Unlike Angular, Vue does not ship with this functionality out of the box. 

Ideally we could re-use this functionality across different components. 

It looks like [mixins](https://vuejs.org/v2/guide/mixins.html) are a good solution for abstracting this. (Other suggestions are welcome!)

See also #92 to ensure proper debounce is in place.

**Comment by charlesbrandt** [comment]
Everything but debouncing is in place. I'm going to go ahead and close this for now. I will be interested to see if debouncing is still necessary with Vue, especially since this operates on results that are already on the client side. Debouncing will still be useful for search operations that result in calls to the backend API.

**Comment by agopu** [comment]
I am in favor of the debounce even if the results are already on the client side - I believe this improves user experience. Lack of it can be disconcerting if a user is still typing their query albeit slowly (and the results start moving chaotically).
