### ISSUE TITLE
SQAN: Vue,js:: AuthN/AuthZ

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#136]

**Comment by youngmd** [comment]
Enabled CAS authentication method with vue app.  Front page allows picking for CAS login or expanding email/password local login form.

**Comment by youngmd** [comment]
Need to add guest login for demo portal.

**Comment by youngmd** [comment]
Guest login is enabled.  Guest user must be manually created for this feature to function.

@charlesbrandt I also have added support for multiple role checking in the store, not just primary_role.  Use `$store.getters.hasRole('admin')"` to check if user has the admin role even if their primary role is set to something else.

**Comment by youngmd** [comment]
VueJS conversion complete.
