### ISSUE TITLE
SQAN: Vue,js:: About page

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#137]

**Comment by youngmd** [comment]
Currently using a modified version of the informatic created for SPIE as the About page.  In the context of the Vue transition this is complete.  Creating an updated and improved About page should be a separate issue.

**Comment by agopu** [comment]
> Currently using a modified version of the informatic created for SPIE as the About page. In the context of the Vue transition this is complete. Creating an updated and improved About page should be a separate issue.

Sounds good - see https://github.com/IUSCA/SQAN/issues/157
