### ISSUE TITLE
SQAN: Vue,js:: Exams view

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#138]

**Comment by youngmd** [comment]
Improved QC Status indicators and added legend.  Added subject filtering to this view.

![Screen Shot 2020-05-08 at 3 35 26 PM](https://user-images.githubusercontent.com/1247513/81442481-aa0b7200-9141-11ea-918b-53f87409f5ce.png)

**Comment by youngmd** [comment]
Exams view is complete for VueJS conversion.
