### ISSUE TITLE
SQAN: Vue,js:: Series Details view

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#139]

**Comment by youngmd** [comment]
Series detail view shows basic information and image blocks at this point.  Image blocks are correctly colored based on their QC status and clicking on an image loads that images header in a searchable table.  Event history and series-level operations (reqc/comment/change template) still needs implementation.

**Comment by youngmd** [comment]
Ended up removing the close button and making this item a separate page/modal.  Added direct link option and addressed template issue described above.
