### ISSUE TITLE
SQAN: Vue,js:: Research Summary view

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#140]

**Comment by youngmd** [comment]
Initial version of this view pulls research id listings and creates a searchable dropdown.  Selecting a research loads a detail card by pulling from the iibis db collection.  Research summary table still needs to be implemented.

**Comment by youngmd** [comment]
Implemented summary table.  

TODO 
- [ ] transpose table (do in API?)
- [ ] rotate table headers
- [ ] export to csv/json

![Screen Shot 2020-04-21 at 3 23 40 PM](https://user-images.githubusercontent.com/1247513/79905459-49abcf00-83e4-11ea-82a3-51006588e919.png)

**Comment by youngmd** [comment]
Fixed issue with modality display
Added export to csv/json functionality

**Comment by youngmd** [comment]
Picking this up again, will see about resolving the 2 remaining TODOs.

**Comment by agopu** [comment]
Removed this from a master ticket though it's mildly related ... we can knock this out as time permits.

**Comment by agopu** [comment]
Closing stake ticket; SQAN has not been as much of a priority and has been in steady state mode. CC @charlesbrandt
