### ISSUE TITLE
SQAN: Vue,js:: Template Summary view

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#141]

**Comment by youngmd** [comment]
What's the status of this @charlesbrandt ?  Has the delete all/selected action been tested?  Are there any remaining TODO items for the Vue transition?

**Comment by charlesbrandt** [comment]
The delete functionality is mostly in place. I'm a little unclear about the desired behavior for "Delete all series". Should the tab for that template exam also be removed? Currently all series will be deleted, but that is all.
