### ISSUE TITLE
SQAN: Vue,js:: QC Criteria Configurator (qckeys view)

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#142]

**Comment by youngmd** [comment]
Initial version of this page has been developed, read-only listing at this point.  Still needs separation into different modalities and admin-level editing.

**Comment by youngmd** [comment]
Sorted into modalities with tabbed interface to move between modality qc scopes

![Screen Shot 2020-04-21 at 3 21 59 PM](https://user-images.githubusercontent.com/1247513/79905219-e91c9200-83e3-11ea-9b0b-5ddccf3cce41.png)

**Comment by youngmd** [comment]
Editing of properties (skip/custom handler) is now enabled.  Form for adding new keys is present, as well as database scan for unregistered keys and batch addition is also functional.  This is functionally equivalent to the previous angularJS version, closing this ticket as any further improvements should be a separate issue.
