### ISSUE TITLE
SQAN: Vue,js:: Dataflow page

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#143]

**Comment by youngmd** [comment]
Initial version of dataflow page is implemented. Improvements over current version include a date range selector (based on N days ago).  

TODO:  

- [ ] add filtering to results table.  
- [ ] Move received image count summation to back end
- [ ] Retrieve series level info on table expand 

![Screen Shot 2020-04-21 at 3 02 18 PM](https://user-images.githubusercontent.com/1247513/79903539-4105c980-83e1-11ea-96ca-e08607947fcd.png)

**Comment by youngmd** [comment]
Added filtering.  Marking this as Done for the Vue transition.  Placed remaining TODOs in separate ticket (see #155)
