### ISSUE TITLE
SQAN: Vue,js:: Data Upload page

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#144]

**Comment by youngmd** [comment]
Added a config option for "upload_enabled" to hide/show the upload menu item.

**Comment by youngmd** [comment]
Implemented upload page as previously developed in angularJS.  Availability of the upload page is determined by the `upload_enabled` key in the Vue `config.js`

![Screen Shot 2020-06-16 at 1 50 56 PM](https://user-images.githubusercontent.com/1247513/84809921-9cff5f80-afd8-11ea-990c-1338679af12e.png)
