### ISSUE TITLE
SQAN: Explore Vuetify UI framework as alternative to Bootstrap

### ISSUE THREAD

**Issue by youngmd** [IUSCA/SQAN#151]
During the recent Vueconf it became apparent that Vuetify was widely accepted as the standard UI framework with Vue, and that going forward it will have better support and tighter integration with Vue 3 than Vue-Bootstrap enjoys.  The conversion of SQAN from angularjs to vue offers an opportunity to also explore a switch in UI framework at an early stage.  To that end I have begun transforming the early Vue SQAN prototype to using the Vuetify framework.  

Early results are promising, particularly in terms of having a clean navigational UI the minifies automatically (only shows icons until mouseover).  I have also added support for the router to automatically switch between a "simple" layout (e.g. signin page) and an "app" layout (most other pages).

**Comment by agopu** [comment]
This sounds very promising, thanks @youngmd!

**Comment by youngmd** [comment]
Converted all existing pages to use Vuetify framework and pushed to Vue branch.  Including screenshots of current build for reference

<img width="819" alt="Screen Shot 2020-03-19 at 4 45 47 PM" src="https://user-images.githubusercontent.com/1247513/77113438-354d6e80-6a01-11ea-8f64-ee978b08615e.png">

<img width="1186" alt="Screen Shot 2020-03-19 at 4 46 03 PM" src="https://user-images.githubusercontent.com/1247513/77113445-38485f00-6a01-11ea-981d-8b9b79ac5c3b.png">

**Comment by youngmd** [comment]
Marking this as Done since we are no longer "exploring" this, having settled on Vuetify moving forward.
