### ISSUE TITLE
SQAN: Admin user actions are not updated in data table

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/SQAN#153]
The access control section leverages vuetify data-tables to display user data. The action column is over-ridden in the UserList.vue component. When navigating from one page of users to the next, the action column does not update as expected. 

For example, navigating to the last page of users and clicking on the 'edit' icon results in editing the user data from the corresponding row from the first page of the table.

**Comment by youngmd** [comment]
It looks like `userdataLocal` is the culprit.  It's not being updated when `userdata` is changed, so I would suggest setting a watcher on `userdata` to update `userdataLocal`.  Normally we'd use a computed property but since we want to mutate `userdataLocal` a watcher is the correct choice here.

**Comment by charlesbrandt** [comment]
Thanks Mike! That was the problem. Adding a watcher fixed the behavior.
