### ISSUE TITLE
SQAN: Update user details results in server error

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/SQAN#154]
When attempting to [issue an http.patch](https://github.com/IUSCA/SQAN/blob/d19cb91798a586f6f536a40533f43f39784fea78/ui/src/components/admin/UserForm.vue) for updating details for a user,

```
        this.$http
          .patch(
            `${this.$config.api}/user/` + this.userdataLocal._id,
            this.userdataLocal
          )
```

Firefox reports:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sqan-test.sca.iu.edu/api/qc/user/5ea3339c8a601b65e7cf46d6. (Reason: CORS request did not succeed).

Error: Network Error
```
I'm planning to explore what's happening at the api level, but thought I'd write it up in case anyone else has encountered this already.

**Comment by youngmd** [comment]
Try this again.  I added PATCH to the nginx Access-Control-Allow-Methods

**Comment by charlesbrandt** [comment]
That fixed it. Thank you!
