### ISSUE TITLE
SQAN:  Reduce Dataflow load on client

### ISSUE THREAD

**Issue by youngmd** [IUSCA/SQAN#155]
The dataflow page is currently very client-heavy, dumping a large amount of data the requires reorganization to display properly.  The UI and API should be modified to send only the data required to display the top-level table, and only pull required lower-level data as rows are expanded by the user.

**Comment by agopu** [comment]
Closing stale ticket; SQAN has not been as much of a priority and has been in steady state mode. CC @charlesbrandt
