### ISSUE TITLE
SQAN: Go back to displaying only error/warning header keywords by default in Image Details view

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#168]
We used to only display only error/warning header keywords by default in Image Details view, we should go back to this.

**Comment by youngmd** [comment]
This has been implemented

![Screen Shot 2020-07-17 at 10 15 39 AM](https://user-images.githubusercontent.com/1247513/87795773-87b76400-c816-11ea-9542-9897db94c246.png)
