### ISSUE TITLE
SQAN: Develop simple script to reQC exams with no template status but with available template

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#173]
As discussed in the meeting w/ Rob today. 

- [x] Develop simple script to reQC exams with no template status but with available template
- [ ] Cron this, say, once a  day.

**Comment by agopu** [comment]
Mike via email

> ​Yes, I selected all of the no_template series that currently have templates and set them to be reQC'd.  The QC process tends to take a kind of scattershot approach when dealing with a large backlog so it may be some time before that exam is completed.

**Comment by agopu** [comment]
@youngmd What should be set to run once a day on cron?

**Comment by youngmd** [comment]
`node /opt/sca/rady-qc/bin/no_template_scan.js`

**Comment by agopu** [comment]
I plan to hold off until after the demo so as to avoid mass reQCes that may be hard to understand from a user perspective.

**Comment by agopu** [comment]
@rperigo could we knock this this stale pending task? (To be clear I let it sit on the backburner)

**Comment by rperigo** [comment]
This is done
