### ISSUE TITLE
SQAN: Update p_CoilString QC criteria (Head Coil, Neck Coil, etc.)

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#176]
From today's meeting w/ Rob Bryant

- We use a 20 [HE1-4] or 32 [HEA and HEP] or 64 [HC1-7] channel head coil. 
- Phantom may have a larger neck thereby causing us to use more coils but on an actual study (exam) we did not have to use all of those coils. 

- QC criteria per Rob - implement ASAP.
  - If HE1-4 -- match for HE<number> (but don’t worry if it’s the exact same number)
  - If HC1-7 -- match for HC<number> (but don’t worry if it’s the exact same number)
  - If HEA/HEP -- match exactly for both HEA/HEP.
  - If BC -- ???

- NOTE: Found one exam where the body coil was used when the head coil should have been!

**Comment by youngmd** [comment]
Added the above criteria.  For the BC case, I fell back to exact string match if the other 3 cases didn't fit.

**Comment by agopu** [comment]
Mike's has already initiated reQCing affected data (specifically series that had been listed as errored out by this QC criterion.)
