### ISSUE TITLE
SQAN: Exclude RequestedProcedureDescription  from QC

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#177]
From today's meeting w/ Rob Bryant
- RequestedProcedureDescription should be excluded from QC.

**Comment by youngmd** [comment]
Set this key to "Skip" using the QC Keys page within the portal.

**Comment by agopu** [comment]
Mike's has already initiated reQCing affected data (specifically series that had been listed as errored out by this QC criterion.)
