### ISSUE TITLE
SQAN: Add a live error frequency display

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#180]
This came up in a RADY zoom call on Nov 2 2020. Rob Bryan, Mario D, and Mike are all interested in a live error frequency display.

(Ticketing so we don't let this slip. Will icebox it for now.)

**Comment by youngmd** [comment]
Initial prototype is available on rady-test.  Gets a live count of the error frequency for each keyword (i.e. how many series affected?).  Expanding details will get a list of affected IIBIS with a subject count.  Expanding further will list each subject/series that that the error appears in, along with a link to directly open that series in a new tab.

![Screen Shot 2021-06-25 at 11 14 29 AM](https://user-images.githubusercontent.com/1247513/123446374-cfa64580-d5a6-11eb-9069-d8bcfad62e0a.png)

There are a number of improvements to be made.  The API call takes a few seconds to return, so I need to add loading icons and investigate how to speed up the search.  The nested tables layout is also not very clear at the moment.  Maybe color code each type of table to more clearly distinguish?  Or move away from table layout completely.  

We should also split by type of error, especially along the lines of missing/template mismatch as those are the two major sources.  I'm considering adding tabs to the top to split by type.  

Date of first/last occurrence could be useful in sorting to look for recent errors.  Potentially we could also show a date graph at both the top level and first detail layer to show overall frequency of errors over time.

**Comment by youngmd** [comment]
Initial version has been pushed to production.  Added date of first/last occurrence, and added colors to headers of the nested tables to visually distinguish them.  Also added search/filtering.

**Comment by agopu** [comment]
@mparamas @kkyoder @rwbryant Please note that a feature that we had discussed in one of our past zoom calls has now been implemented (thanks Mike!) -- QC error count statistics are now listed on the portal via a new menu item.

![image](https://user-images.githubusercontent.com/2206370/124319627-7f038f00-db48-11eb-9c69-30bd6ef6296f.png)

Please let us know if you have any questions or comments.

**Comment by agopu** [comment]
We've not heard back from @mparamas @rwbryant or @kkyoder but assume the feature is working as they would like it to, I am closing this ticket.
