### ISSUE TITLE
SQAN: Custom landing page depending on who the user is

### ISSUE THREAD

**Issue by agopu** [IUSCA/SQAN#181]
We have discussed allowing a user to pick the page that is shown by default up on logging in. This would be the ideal case scenario.

For now, we may just modify the landing page to be the calendar view for ALL users or at least Technologist type users.

**Comment by youngmd** [comment]
The calendar page has been the default landing on production for a while now, and it appears to be generally satisfactory.  Moving this ticket to icebox in case we decide to implement this feature at some point in the future.

**Comment by agopu** [comment]
Closing stale ticket; SQAN has not been as much of a priority and has been in steady state mode. CC @charlesbrandt
