### ISSUE TITLE
RADY: Add 'Contact PI' option

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/SQAN#84]
During a couple of meetings with technologists and PI's, we've talked about the possibility of adding a button in the Series (and maybe the Exam) view, that would allow the technologist to contact the research PI when in doubt of some QC error/issue. 

In our last meeting with Researchers, this idea was not fully supported, as it seemed like the MR experts were skeptical about PI's having knowledge about the nature of errors in the data. 

Perhaps the 'Contact' button should allow the technologist to contact an MR/PT/CT expert, as opposed to the PI?

**Comment by agopu** [comment]
@aiavenak worked on this and will fill in details so/before we (can) push to production.
