### ISSUE TITLE
RADY: Improve Access Control for technologists/researchers to view/QC

### ISSUE THREAD

**Issue by aiavenak** [IUSCA/SQAN#86]
Updated 2019-06-07: We will likely update the UI for access control so we can set a particular user to have view and/or QC access to a particular set of IIBIS IDs.

Overall, we will use as much of our experience and knowledge access control on the ODI portal to the RADY project.

---
Currently, all RADY-SCA users have access to viewing and editing all the data. We need to change this so that users only have access to specific IIBISID's. 

In addition, we'd like to allow users to be able to set their preferences, for example, users may want to always how or not show deprecated series, or may want to, by default, show all data acquired in the last year, as opposed to just 30 day default.

**Comment by agopu** [comment]
Still waiting on #96 so moving to icebox.

**Comment by agopu** [comment]
Closing stale ticket; SQAN has not been as much of a priority and has been in steady state mode. CC @charlesbrandt
